# Generated by Django 5.0.6 on 2024-06-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PageConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_page", models.IntegerField()),
                ("target_page", models.IntegerField()),
                ("similarity", models.FloatField()),
                (
                    "pdf_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pdffile"
                    ),
                ),
            ],
        ),
    ]
