# Generated by Django 5.0.6 on 2024-07-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="group",
            field=models.IntegerField(null=True),
        ),
    ]
