# This is a basic workflow to help you get started with Actions
name: CI/CD Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python:
    name: Python CI/CD
    runs-on: ec2
    environment: JUNGLE_SECRET
    defaults:
      run:
        working-directory: ./django-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.12"

      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.PYTHON_SECRET_KEY }}" >> .env 
          echo "AWS_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY }}" >> .env 
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_S3_REGION_NAME=${{ secrets.AWS_REGION }}" >> .env 
          echo "AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_BUCKET }}" >> .env 
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env 
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env 
          echo "DATABASE_ENGINE=${{vars.DATABASE_ENGINE}}" >> .env 
          echo "DATABASE_NAME=${{vars.DATABASE_NAME}}" >> .env 
          echo "DATABASE_HOST=${{vars.DATABASE_HOST}}" >> .env 
          echo "DATABASE_PORT=${{vars.DATABASE_PORT}}" >> .env 
          cat .env

      - name: docker Down
        run: docker compose down

      - name: docker remove image
        run: docker rmi nmm_django
        continue-on-error: true

      - name: docker up
        run: docker compose up -d --build

      - name: remove .env file
        run: rm .env
        continue-on-error: true
